version: '3'
services:
  web:
    build: .
    platform: linux/x86_64
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db
    command:  ./start.sh

  db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: postgres

      volumes:
        - postgres_data:/var/lib/postgresql/data/
  front:
     build:
       context: ./front
       target: 'develop-stage'
     ports:
     - '8080:8080'
     command: /bin/sh -c "yarn serve"
volumes:
  postgres_data:
