version: '3.8'
services:
  web:
    build: .
    command: python /project/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/project
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: postgres
      
      volumes:
        - postgres_data:/var/lib/postgresql/data/
  front:
    build:
      context: ./front
      target: 'develop-stage'
    ports:
    - '8080:8080'
    command: /bin/sh -c "yarn serve"
volumes:
  postgres_data:
